### ISSUE TITLE
Error "Profile isn't available" just after logging in

### ISSUE THREAD

**Issue by elsa-ssg** [dinsic-pim/tchap-ios#219] opened 2019-07-08 13:21 UTC
Multiple users have an error message "profile is not available" right after logging in. The screen remains blocked on this error message so the application is unusable on the terminals concerned. Sometimes they also have "Connexion impossible au serveur d’accueil" but it is not systematic.

**Comment by elsa-ssg** [comment] 2019-07-08 13:40
![IMG_20190705_122408](https://user-images.githubusercontent.com/48802291/60814825-a8c28f00-a196-11e9-8d59-874d9c38ac86.jpg)
![IMG_20190705_122457 (1)](https://user-images.githubusercontent.com/48802291/60814834-ac561600-a196-11e9-9b78-b1bf5dd88f5c.jpg)

**Comment by giomfo** [comment] 2019-07-08 16:03
Note: I just reproduced this by creating a new account

**Comment by babolivier** [comment] 2019-07-08 16:09
This error is only returned by https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/handlers/profile.py#L283, which itself is only called when the user tried to make a request to a `/profile` endpoint.

My hunch is that the app is trying to query the profile of the user that just auth'd and it fails because there's no room yet. Then Synapse considers that we don't share a room with ourselves yet, and therefore denies the request.

**Comment by babolivier** [comment] 2019-07-08 16:52
Right, so that's indeed the issue. There's a patch for Synapse waiting for review: https://github.com/matrix-org/synapse/pull/5644

Once that's accepted and merged I'll port it to the `dinsic` branch and merge it there as well.

**Comment by giomfo** [comment] 2019-07-12 10:37
done

**Closed by giomfo** 2019-07-12 10:37 UTC
